server:
  port: 8080
  servlet:
    encoding:
      force-response: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_RDS_URL}
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}
#    url: jdbc:mysql://localhost:3306/main012?serverTimezone=Asia/Seoul
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
logging:
  level:
    org:
      springframework:
      orm:
        jpa: DEBUG
  file:
    path: /home/ubuntu/log

#jwt:
#  key: ${JWT_SECRET_KEY}
#  access-token-expiration-minutes: 30
#  refresh-token-expiration-minutes: 720
#
#mail:
#  address:
#    admin: admin@gmail.com
#config:
#  domain: ${AWS_S3_ENDPOINT}