server:
  port: 8080
  servlet:
    encoding:
      force-response: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_RDS_URL}
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}
  #    url: jdbc:mysql://localhost:3306/main012?serverTimezone=Asia/Seoul
  #    username: ${MYSQL_USERNAME}
  #    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
logging:
  level:
    org:
      springframework:
      orm:
        jpa: DEBUG
  file:
    path: /home/ubuntu/log
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_IMAGE_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  key: ${JWT_SECRET_KEY}
  access:
    expiration: 7200000 # 1000(ms) * 60(s) * 60(minute) * 2(hour) = 7200000
    header: Authorization
  refresh:
    expiration: 43200000 # 1000(ms) * 60(s) * 60(minute) * 12(hour)
    header: Authorization-Refresh

mail:
  address:
    admin: admin@email.com
#config:
#  domain: ${AWS_S3_ENDPOINT}